# This is a basic platformio build workflow

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    
    - name: Set up Python
      uses: actions/setup-python@v1
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Install platformIO libraries
      run: pio pkg install
    
    - name: Run PlatformIO
      run: platformio run
